[package]
name = "replacing-netcat"
version = "0.1.0"
authors = ["Luke <nineofpine@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3" # command line argument parser
